name: lms
version: 1.0.0+4
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  http: ^1.1.0
  get_storage: ^2.1.1
  cached_network_image: ^3.2.3
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  intl: ^0.18.1
  camera: ^0.10.5+2
  image: ^4.0.17
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.1.12
  file_picker: ^5.3.3
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/icons/icon_launcher.png"
  android: true
  ios: false

flutter_native_splash:
  color: "#071759"
  image: assets/icons/Logo.png
  android: true
  ios: true
  android_12:
    background_color: "#071759"
    foreground_color: "#071759"
    dark: true

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
